# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
puts "Seeding the shopping spree"

User.destroy_all
Cart.destroy_all
CartItem.destroy_all
Item.destroy_all
Review.destroy_all

u1 = User.create(first_name: "Najma", last_name: "A", username: "Admin", email: "najma.a16@gmail.com", password: "1234")

c1= Cart.create(user_id: u1.id)

item1= Item.create(name: "Celestial Desktop Timekeepers", cost: "40.00",  image:"https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQnZ4AJA2tV7LKK6sErr_S2DjJZWoPg-HIykqRe_RqWYo2dFl-D0eSnqJ2ZEKOwuRiX_r7G3ahD_dxqowim_Qox3Dt3t7H2mA&usqp=CAY", description: "Pinpoint the time by looking to the heavens with one of two desktop-sized historical clock replicas. The Astronomical Ring Dial is a 17th-century spherical sundial, while the Nocturlabe is based on a 16th-century artifact on display at the British Museum in London. Each brass-dipped, hanging instrument offers an analog method of establishing the current time. The Astronomical Rings use your position in relation to the sun to cast a ray of light through the device onto its timekeeping dials. When darkness falls, the Nocturlabe determines the hour and minute by aligning with stars found in the Big Dipper and Little Dipper. Vanished from use after the late 18th century, these working reproductions offer a link to our technological past and the spirit of transoceanic exploration. ")
Item.create(name: "Mini Celestial Candle Set", cost: "24.99",  image:"https://images.urbndata.com/is/image/UrbanOutfitters/69026714_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=640", description: "Channel out-of-this-world vibes when you display this set of celestial candles rendered in mini size. Features Saturn, Man in the Moon and star-shaped candles. Unscented.")
Item.create(name: "Wall Mounted Candle Holder", cost: "29.00",  image:"https://images.urbndata.com/is/image/UrbanOutfitters/69645869_007_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=640", description: "Channel the power of the sun and moon when you display your favorite taper candle in this wall-mounted candle holder featuring a celestial frame. Fitted with a rounded dish that holds one taper candle.")
Item.create(name: "Gold Catch-All Dish", cost: "8.00",  image:"https://images.urbndata.com/is/image/UrbanOutfitters/61808754_070_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=640", description: "Let your twinkly treasures shine in this round metal catch-all dish. Rendered in a high-shine finish with raised edges, it features etched celestial motifs that are so dreamy.")
Item.create(name: "Vinyl Record Shelf", cost: "109.00",  image:"https://images.urbndata.com/is/image/UrbanOutfitters/79519245_070_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=640", description: "Take your décor to the moon with this storage rack that holds your vinyl collection and turntable with celestial appeal. Crafted from metal with stars and moons sculpted on the sides, this storage rack features a trio of shelves with separators at the base.")
Item.create(name: "Man On The Moon Incense Holder + Ashtray Set", cost: "18.00",  image:"https://images.urbndata.com/is/image/UrbanOutfitters/47606967_070_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=640", description: "Set your sights on the stars with this vintage-look incense holder and ashtray set. Featuring 2 dishes - a crescent moon and man in the full moon, both made in a high-shine finish stoneware with etched detailing.")
Item.create(name: "Emanuela Carratoni La Lune Art Print", cost: "35.00",  image:"https://images.urbndata.com/is/image/UrbanOutfitters/49149594_002_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=640", description: "Stargaze with this lunar graphic art print from Emanuela Carratoni. Printed on archival paper made from cotton pressed in Italian mills, this high-quality art print is available 13x19 with a modern black frame, just right for your space!")
Item.create(name: "Crystal Ball Desktop Ornament", cost: "55.99",  image:"https://img.staticdj.com/89b88d389700d07f61c1de8dd3254910_1080x.jpeg", description: "According to our luxurious celestial crystal ball, the future looks stormy. The glass ball works like a plasma earth: as the “lightning” moves along the surface of the finger, what follows the finger is a dazzling blue electricity emanating from its center.For a long time, thunder rolled around on the pedestal, and a group of witches seemed to hold their destiny in the cold, gem-like grip of fate.")
Item.create(name: "Large Celestial Suncatcher", cost: "44.44",  image:"https://www.danibeefunky.com/uploads/1/2/5/3/125386070/s498233186107191308_p2768_i1_w2000.jpeg?width=800", description: "Let the sunshine in and color your world! Our Large Celestial Suncatcher is a great way to brighten your day. When bright sunlight hits this prism, it transforms the light into beautiful rainbows.It is ideal to hang by the window in any room.Perfect as a gift!")
Item.create(name: "Mixed Earring Set", cost: "10.00",  image:"https://images.urbndata.com/is/image/UrbanOutfitters/76178185_070_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=640", description: "Create an effortless ethereal mix with this 8-piece earring pack designed in celestial themes. Includes mini hoops, studs and dangly drops for ultimate layering.")
Item.create(name: "Diamond Sun and Moon Necklace in 10k Gold", cost: "350.00",  image:"https://www.zales.com/productimages/processed/V-20353527_0_800.jpg?pristine=true", description: "Illuminate her celestial style with this gemstone sun and moon pendant. Fashioned in warm 10K gold, this look showcases a 3.5mm iridescent opal centered in a sun-style frame embraced by shimmering diamond-adorned rays. Additional diamonds grace the stars, sun, and crescent moon-shaped stations. Radiant with 1/6 ct. t.w. of diamonds and a brilliant buffed luster, this design suspends centered along an 18.0-inch cable chain that secures with a lobster claw clasp.")
Item.create(name: "Face full of Stars Print", cost: "32.99",  image:"https://i.etsystatic.com/35944533/r/il/af6d66/4471948156/il_794xN.4471948156_be4t.jpg", description: "A print is a perfect way to showcase who you are on the inside. These matte-finish posters will bring some ✨sparkle✨ to any space.")
Item.create(name: "The Universe Unveiled Print", cost: "25.00",  image:"https://i.pinimg.com/640x/7d/e8/16/7de816238631ff3d82dc99c2693eaa68.jpg", description: "Vintage-inspired celestial art print, perfect for anyone who loves the mystery and wonder of the universe! Featuring intricate designs of old school moons, stars, and other celestial concepts, this art print has a dreamy, nostalgic feel that is sure to inspire contemplation and curiosity.Printed on high-quality paper using archival inks, this art print is designed to last and maintain its vibrant colors for years to come.")
Item.create(name: "Opal Star Necklace", cost: "40.80",  image:"https://i.etsystatic.com/5991432/r/il/22d595/4174007888/il_794xN.4174007888_1j7z.jpg", description: "This gold opal star necklace is an exquisite piece of jewelry that will add a touch of elegance and sophistication to any outfit. The pendant features a delicate star shape, crafted from high-quality gold and adorned with a dazzling opal stone at its center. The opal stone has a natural iridescence that catches the light beautifully, making this necklace a true statement piece that will draw compliments and admiration wherever you go.")
Item.create(name: "Pearl Gold Earrings", cost: "22.99",  image:"https://i.etsystatic.com/7958084/r/il/6f2018/2787740375/il_794xN.2787740375_2q9k.jpg", description: "These gorgeous sparkly gold stars earrings will make a beautiful addition to your jewelry collection or a wow-worthy gift for a friend or a bridesmaid. Stylish, highly detailed, lightweight, and elegant, these trendy earrings will get noticed and draw compliments. 24K gold plated brass stars glisten and catch the light beautifully, whilst remaining classy, chic, and understated")
Item.create(name: "Sun and Moon Candle", cost: "11.72",  image:"https://i.etsystatic.com/29243306/r/il/20074d/3079840115/il_794xN.3079840115_9vcs.jpg", description: "Our Emma Sun and Moon Candle is for all of the celestial dreamers. Each candle comes with a plantable seed paper moon that grows wildflowers!")
Item.create(name: "Pillar Shaped Candle Set", cost: "24.99",  image:"https://images.urbndata.com/is/image/UrbanOutfitters/69840080_018_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=640", description: "Take your décor out of this world with this set of unscented candles shaped like a celestial sun and moon in a pillar-style silhouette. Available exclusively at Urban Outfitters")
Item.create(name: "Moon Child Halo", cost: "150.00",  image:"https://i.etsystatic.com/14484194/r/il/b01c0f/3256704801/il_1588xN.3256704801_tv2w.jpg", description: "This celestial headpiece is a stunning accessory that will make you feel like a goddess. The headpiece features a delicate, intricate design that is inspired by the celestial bodies of the universe, with a focus on the moon and stars. The high-quality gold finish gives it an ethereal, otherworldly look that will add a touch of magic and whimsy to any outfit or occasion.")
Item.create(name: "The Sun God & Moon Goddess Collection", cost: "45.00",  image:"https://cdn.shopify.com/s/files/1/0599/0793/2348/products/IMG_6485_1080x.jpg?v=1647416726", description: "Celebrate the Sun God & Moon Goddess with our mystical gold foil celestial candles.These soy wax scented candles are a must have for your home. With rich intoxicating scents and a burn time of up to 45 hours, these stunning candles are sure to keep you feeling warm and revitalised whilst encouraging time for you to unwind and reflect. ")
Item.create(name: "Galaxy Comb", cost: "67.00",  image:"https://i.etsystatic.com/5768001/r/il/3778cb/2615224286/il_1588xN.2615224286_s6pw.jpg", description: "An arrangement of the cosmos on a gold plated comb. Featuring moon and stars, with moonstone and laboradorite stones.")
Item.create(name: "Magic Dragon Print", cost: "34.00",  image:"https://cdn.shopify.com/s/files/1/0561/8477/products/Magic-Dragon_1512x.jpg?v=1547045468", description: "The Dragon is arguably the most ancient and imposing animal spirit guide.The European folklore has portrayed the dragons as evil, fearsome and malevolent creatures and the Asian cultures regard them as benevolent beings.As a symbol, the Dragon represents strength, fortune, authority, growth, luck to those who work hard and development. Dragon is a rare and powerful Spirit Animal and is drawn to people of intellect, dignity, contagious enthusiasm and authority.All Dragon spirits have alchemical power, which means they hope to turn you into “gold” spiritually. Dragon will protect you when you work for the greatest good, but woe to those who begin reaching for power greedily.To the Druids, Dragons represented vitality, the psychic self, ancient wisdom and the power of creation itself. Stories of Dragons protecting the secret and sacred entryways to other realms are common in Celtic and Druid folklore.")

CartItem.create(cart_id: c1.id, item_id: item1.id, quantity: 1)

Review.create(user_id: User.first.id, item_id: Item.first.id, comment: "Stunning! I'm absolutely in love with it!!", rating: 5)

puts "Shopping spree completed successfully"